packages:
  - packages/*
  - examples/*
  - website

allowBuilds:
  esbuild: true
  msgpackr-extract: false

onlyBuiltDependencies:
  - esbuild
catalog:
  "@effect/platform": ^0.96.2
  "@effect/rpc": ^0.75.1
  "@types/node": ^25.9.2
  effect: ^3.21.4
  tsx: ^4.23.0
  typescript: ^6.0.3
  vite-plus: 0.2.2
  vite: npm:@voidzero-dev/vite-plus-core@0.2.2
  vitest: 4.1.9
  "@vitest/browser-playwright": 4.1.9
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
minimumReleaseAgeExclude:
  - "@voidzero-dev/vite-plus-core@0.2.2"
  - "@voidzero-dev/vite-plus-darwin-arm64@0.2.2"
  - "@voidzero-dev/vite-plus-darwin-x64@0.2.2"
  - "@voidzero-dev/vite-plus-linux-arm64-gnu@0.2.2"
  - "@voidzero-dev/vite-plus-linux-arm64-musl@0.2.2"
  - "@voidzero-dev/vite-plus-linux-x64-gnu@0.2.2"
  - "@voidzero-dev/vite-plus-linux-x64-musl@0.2.2"
  - "@voidzero-dev/vite-plus-win32-arm64-msvc@0.2.2"
  - "@voidzero-dev/vite-plus-win32-x64-msvc@0.2.2"
  - vite-plus@0.2.2
